[workspace]
members = [
    "sigmac-lib",
    "sigmac-cli",
    "sigmac-api-server",
    "sigmac_frontend"
]

[profile.dev]
opt-level = 3

[profile.release]
codegen-units = 1
debug-assertions = false
debug = false
opt-level = 3
lto = true